### ISSUE TITLE
Loosen Meta Strings order requirement

### ISSUE THREAD

**Issue by o-az** [rehype-pretty/rehype-pretty-code#191]
this `title="fib.sh" showLineNumbers /index/#v` works but this `/index/#v title="fib.sh" showLineNumbers` doesn't.

In general `showLineNumbers` does not work when there's a highlighted group chars and and the highlighted group chars does not come after `showLineNumbers`.

- [ ] go through all permutations of possible meta strings,
- [ ] note down the orderings that don't work,
- [ ] fix or if not possible add specific comment / "heads up" in docs
